version: '3.8'

services:
  agriflow-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - agriflow-api-db
    networks:
      - agriflow-network


  agriflow-api-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agriflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agriflow-network

volumes:
  postgres_data:
networks:
  agriflow-network:
    driver: bridge 
