import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCropFields1750793500217 implements MigrationInterface {
    name = 'AddCropFields1750793500217'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "crops" DROP CONSTRAINT "FK_04cb88149f2872e0d44f3dded98"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_users_role"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" DROP CONSTRAINT "FK_a9d34f1384816fa07ddcde46ff5"`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" DROP CONSTRAINT "FK_b21802e2e08244a54e72736d63c"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" DROP CONSTRAINT "FK_650c050b3e5a3e011549c413977"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d34f1384816fa07ddcde46ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b21802e2e08244a54e72736d63"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" RENAME COLUMN "crop_id" TO "id_crop"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" RENAME CONSTRAINT "PK_e9981c030c895cbef2347571d1c" TO "PK_bd74a3bf1695e5b9e0e90d15c18"`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" RENAME COLUMN "crop_id" TO "id_crop"`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" RENAME CONSTRAINT "PK_d08bb902898e0074470ebb0ef2b" TO "PK_f39cad08085ceab2dff8299d87b"`);
        await queryRunner.query(`ALTER TABLE "soil_cover" DROP COLUMN "soilCoverDate"`);
        await queryRunner.query(`ALTER TABLE "soil_cover" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "soil_cover" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "soil_cover" DROP COLUMN "soilCoverCommentary"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP CONSTRAINT "PK_098dbeb7c803dc7c08a7f02b805"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "plant_date"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "status_id"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "commentary"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "plant_family"`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "id_crop" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crops" ADD CONSTRAINT "PK_7401d1073c9cee07c784e9dda9b" PRIMARY KEY ("id_crop")`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "family" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "growth_time" integer`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "planting_depth" double precision`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "spacing" double precision`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "row_spacing" double precision`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "optimal_temperature" double precision`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "optimal_ph" double precision`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "water_needs" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "sun_exposure" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_length" integer`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_width" integer`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_soil_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_ph" integer`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_soil_fertility" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_soil_drainage" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD "cultivation_spaces_status" text`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ALTER COLUMN "id_soil_cover" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ALTER COLUMN "type_soil_cover" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crops" ALTER COLUMN "variety" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cultivation_beds" DROP CONSTRAINT "FK_c3a022075a6184f9d0a3812bb90"`);
        await queryRunner.query(`ALTER TABLE "agricultural_actions" DROP CONSTRAINT "FK_63b496aaeaadd0cc23e40602d27"`);
        await queryRunner.query(`ALTER TABLE "observations" DROP CONSTRAINT "FK_be7a041dc83e75a98c01c0f15d6"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP CONSTRAINT "FK_9d703902d2da883cdb4eb8e8885"`);
        await queryRunner.query(`ALTER TABLE "observations" DROP CONSTRAINT "FK_e07b7d26d4ba41193717cfd56c3"`);
        await queryRunner.query(`ALTER TABLE "land" ALTER COLUMN "id_land" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "land" DROP COLUMN "land_area"`);
        await queryRunner.query(`ALTER TABLE "land" ADD "land_area" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "land" DROP COLUMN "land_coordinate"`);
        await queryRunner.query(`ALTER TABLE "land" ADD "land_coordinate" integer`);
        await queryRunner.query(`ALTER TABLE "land" DROP CONSTRAINT "FK_02f9a5dcc539c5571d165e72ed7"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id_user" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Role" ALTER COLUMN "role_name" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_f764a35f95a97d558937f008b6" ON "is_cultivated" ("id_crop") `);
        await queryRunner.query(`CREATE INDEX "IDX_6291d4993512ea0a6323a0b3f1" ON "cultivation_bed_crops" ("id_crop") `);
        await queryRunner.query(`ALTER TABLE "cultivation_beds" ADD CONSTRAINT "FK_c3a022075a6184f9d0a3812bb90" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD CONSTRAINT "FK_9d703902d2da883cdb4eb8e8885" FOREIGN KEY ("land_id") REFERENCES "land"("id_land") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land" ADD CONSTRAINT "FK_02f9a5dcc539c5571d165e72ed7" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_ace513fa30d485cfd25c11a9e4a" FOREIGN KEY ("role") REFERENCES "Role"("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observations" ADD CONSTRAINT "FK_be7a041dc83e75a98c01c0f15d6" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observations" ADD CONSTRAINT "FK_e07b7d26d4ba41193717cfd56c3" FOREIGN KEY ("land_id") REFERENCES "land"("id_land") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agricultural_actions" ADD CONSTRAINT "FK_63b496aaeaadd0cc23e40602d27" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" ADD CONSTRAINT "FK_f764a35f95a97d558937f008b6a" FOREIGN KEY ("id_crop") REFERENCES "crops"("id_crop") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" ADD CONSTRAINT "FK_650c050b3e5a3e011549c413977" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" ADD CONSTRAINT "FK_6291d4993512ea0a6323a0b3f1b" FOREIGN KEY ("id_crop") REFERENCES "crops"("id_crop") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" DROP CONSTRAINT "FK_6291d4993512ea0a6323a0b3f1b"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" DROP CONSTRAINT "FK_650c050b3e5a3e011549c413977"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" DROP CONSTRAINT "FK_f764a35f95a97d558937f008b6a"`);
        await queryRunner.query(`ALTER TABLE "agricultural_actions" DROP CONSTRAINT "FK_63b496aaeaadd0cc23e40602d27"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "observations" DROP CONSTRAINT "FK_e07b7d26d4ba41193717cfd56c3"`);
        await queryRunner.query(`ALTER TABLE "observations" DROP CONSTRAINT "FK_be7a041dc83e75a98c01c0f15d6"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_ace513fa30d485cfd25c11a9e4a"`);
        await queryRunner.query(`ALTER TABLE "land" DROP CONSTRAINT "FK_02f9a5dcc539c5571d165e72ed7"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP CONSTRAINT "FK_9d703902d2da883cdb4eb8e8885"`);
        await queryRunner.query(`ALTER TABLE "cultivation_beds" DROP CONSTRAINT "FK_c3a022075a6184f9d0a3812bb90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6291d4993512ea0a6323a0b3f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f764a35f95a97d558937f008b6"`);
        await queryRunner.query(`ALTER TABLE "Role" ALTER COLUMN "role_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id_user" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land" ADD CONSTRAINT "FK_02f9a5dcc539c5571d165e72ed7" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land" DROP COLUMN "land_coordinate"`);
        await queryRunner.query(`ALTER TABLE "land" ADD "land_coordinate" double precision`);
        await queryRunner.query(`ALTER TABLE "land" DROP COLUMN "land_area"`);
        await queryRunner.query(`ALTER TABLE "land" ADD "land_area" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "land" ALTER COLUMN "id_land" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "observations" ADD CONSTRAINT "FK_e07b7d26d4ba41193717cfd56c3" FOREIGN KEY ("land_id") REFERENCES "land"("id_land") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ADD CONSTRAINT "FK_9d703902d2da883cdb4eb8e8885" FOREIGN KEY ("land_id") REFERENCES "land"("id_land") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "observations" ADD CONSTRAINT "FK_be7a041dc83e75a98c01c0f15d6" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agricultural_actions" ADD CONSTRAINT "FK_63b496aaeaadd0cc23e40602d27" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_beds" ADD CONSTRAINT "FK_c3a022075a6184f9d0a3812bb90" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crops" ALTER COLUMN "variety" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ALTER COLUMN "type_soil_cover" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ALTER COLUMN "id_soil_cover" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_status"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_soil_drainage"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_soil_fertility"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_ph"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_soil_type"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_width"`);
        await queryRunner.query(`ALTER TABLE "cultivation_spaces" DROP COLUMN "cultivation_spaces_length"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "sun_exposure"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "water_needs"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "optimal_ph"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "optimal_temperature"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "row_spacing"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "spacing"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "planting_depth"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "growth_time"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "family"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP CONSTRAINT "PK_7401d1073c9cee07c784e9dda9b"`);
        await queryRunner.query(`ALTER TABLE "crops" DROP COLUMN "id_crop"`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "plant_family" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "commentary" text`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "status_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "plant_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crops" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "crops" ADD CONSTRAINT "PK_098dbeb7c803dc7c08a7f02b805" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ADD "soilCoverCommentary" text`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "soil_cover" ADD "soilCoverDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" RENAME CONSTRAINT "PK_f39cad08085ceab2dff8299d87b" TO "PK_d08bb902898e0074470ebb0ef2b"`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" RENAME COLUMN "id_crop" TO "crop_id"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" RENAME CONSTRAINT "PK_bd74a3bf1695e5b9e0e90d15c18" TO "PK_e9981c030c895cbef2347571d1c"`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" RENAME COLUMN "id_crop" TO "crop_id"`);
        await queryRunner.query(`CREATE INDEX "IDX_b21802e2e08244a54e72736d63" ON "cultivation_bed_crops" ("crop_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9d34f1384816fa07ddcde46ff" ON "is_cultivated" ("crop_id") `);
        await queryRunner.query(`ALTER TABLE "is_cultivated" ADD CONSTRAINT "FK_650c050b3e5a3e011549c413977" FOREIGN KEY ("cultivation_space_id") REFERENCES "cultivation_spaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivation_bed_crops" ADD CONSTRAINT "FK_b21802e2e08244a54e72736d63c" FOREIGN KEY ("crop_id") REFERENCES "crops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "is_cultivated" ADD CONSTRAINT "FK_a9d34f1384816fa07ddcde46ff5" FOREIGN KEY ("crop_id") REFERENCES "crops"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_users_role" FOREIGN KEY ("role") REFERENCES "Role"("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crops" ADD CONSTRAINT "FK_04cb88149f2872e0d44f3dded98" FOREIGN KEY ("status_id") REFERENCES "crop_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
